[project]
name = "backendflask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "psycopg>=3.3.2",
    "pydantic-settings>=2.12.0",
    "sqlmodel>=0.0.33",
]
